<<<<<<< HEAD
# Generated by Django 3.2.5 on 2021-07-05 08:08
=======
# Generated by Django 3.2.5 on 2021-07-06 10:02
>>>>>>> a110434d1ef90b6259f3a5920570c6528eccd2be

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
<<<<<<< HEAD
=======
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=20, null=True)),
                ('birth', models.DateField(null=True)),
                ('signup_at', models.DateTimeField(auto_now_add=True)),
>>>>>>> a110434d1ef90b6259f3a5920570c6528eccd2be
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
