# Generated by Django 3.2.5 on 2021-07-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(default='yerang.com', max_length=200),
            preserve_default=False,
        ),
    ]
